### ISSUE TITLE
FEATURE REQUEST: Delete messages

### ISSUE THREAD

**Issue by ironman9356** [Engineer152/DPG-Bot-Slash#2]
Feature request : Make a slash command to delete messages use able by MVP+  required arg message id 

it can put the thing in mod logs if needed 

reason : there can be times where the mods or admins are not available but there can be non server safe stuff posted 
it can replace the report system if not want to be deleted

**Comment by Engineer152** [comment]
I'm not making this change as of now.

**Comment by ironman9356** [comment]
> I'm not making this change as of now.

umm ok
